### ISSUE TITLE
box-sizing: border-box; missing from Timeline header

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#3238]
Hi because we no longer include 
@defencedigital/css-framework which has a global style of 

```css
* {
    box-sizing: border-box;
 }
```
When using the DS in isolation this cause the dates to misalign. 

https://codesandbox.io/s/timeline-box-sizing-demo-r86xep
